<a href="https://colab.research.google.com/github/Danae-Munoz/Analisis_Data_Mineria-de-datos/blob/main/Evaluaci%C3%B3n_1_Danae_Mu%C3%B1oz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Calificación y precio del vino**

**URL:** https://www.kaggle.com/datasets/budnyak/wine-rating-and-price

In [40]:
# Importación de las librerias necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [33]:
# read data
red = pd.read_csv('Red.csv')
white = pd.read_csv('White.csv')
sparkling = pd.read_csv('Sparkling.csv')
rose = pd.read_csv('Rose.csv')

Esta dataset se divide en 4 csv y me gustaria trabajar con los datos como unico

In [34]:
red['WineStyle'] = 'red'
white['WineStyle'] = 'white'
sparkling['WineStyle'] = 'sparkling'
rose['WineStyle'] = 'rose'
df_wines =  pd.concat([red, white, sparkling, rose], ignore_index=True)

In [43]:
# Guardamos nuestro dataframe unificado
df_wines.to_csv('df_wines.csv', index=False)

In [45]:
# Para ver todas las columnas sin cortes
pd.set_option('display.max_columns', None)

# Para ver todas las filas (cuidado si el dataset es muy grande)
pd.set_option('display.max_rows', None)

In [76]:
# Ver informacion del dataframe
df_wines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13834 entries, 0 to 13833
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             13834 non-null  object
 1   Country          13834 non-null  object
 2   Region           13834 non-null  object
 3   Winery           13834 non-null  object
 4   Rating           13834 non-null  float64
 5   NumberOfRatings  13834 non-null  int64
 6   Price            13834 non-null  float64
 7   Year             13834 non-null  float64
 8   WineStyle        13834 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 972.8+ KB

In [78]:
# Visualizamos las primeras 5 filas
df_wines.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,WineStyle
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011.0,red
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017.0,red
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015.0,red
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019.0,red
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016.0,red

In [77]:
# Visualizamos las ultimas 5 filas
df_wines.tail()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,WineStyle
13829,Côte des Roses Rosé 2019,France,Languedoc,Gérard Bertrand,3.9,1750,9.36,2019.0,rose
13830,M Rosé 2019,France,Côtes de Provence,Minuty,4.0,2046,12.85,2019.0,rose
13831,Whispering Angel Rosé 2019,France,Côtes de Provence,Château d'Esclans,4.2,2990,16.47,2019.0,rose
13832,Vinho Verde Rosé N.V.,Portugal,Vinho Verde,Casal Garcia,3.5,9493,4.35,2016.0,rose
13833,The Original Rosé N.V.,Portugal,Douro,Mateus,3.6,29531,5.99,2016.0,rose

In [60]:
# Devuelve la cantidad de filas y columnas respectivamente
df_wines.shape

(13834, 9)

Este dataframe tiene 13.834 filas y 9 columnas

In [69]:
# Observamos la columna y sus tipos de datos
df_wines.dtypes

Name                object
Country             object
Region              object
Winery              object
Rating             float64
NumberOfRatings      int64
Price              float64
Year               float64
WineStyle           object
dtype: object

In [52]:
# Contamos la cantidad de nulos por columna
df_wines.isnull().sum()

Name               0
Country            0
Region             0
Winery             0
Rating             0
NumberOfRatings    0
Price              0
Year               0
WineStyle          0
dtype: int64

Podemos observar que el dataframe no tiene nulos, pero en el apartado de año, tiene N.V (sin año específico), vamos a solucionarlo

In [64]:
# Revisar qué valores raros tiene Year
df_wines['Year'].unique()

array([2011., 2017., 2015., 2019., 2016., 2014., 2013., 2018., 2012.,
       2010., 2007., 2005., 1999., 2002., 2008., 2006., 2009.,   nan,
       2000., 2004., 2001., 1996., 1998., 1990., 1995., 2003., 1993.,
       1988., 1989., 1997., 1992., 1991., 2020., 1961.])

In [63]:
# Transformar Year a numérico
df_wines['Year'] = pd.to_numeric(df_wines['Year'], errors='coerce')

In [99]:
# Ver cuántos nulos aparecieron
df_wines.isnull().sum()

Country            0
Region             0
Rating             0
NumberOfRatings    0
Price              0
Year               0
WineStyle          0
dtype: int64

Luego de la transformacion de la columna Year de categorica a numerica podemos observar que tenemos 744 nulos en total

**Desicion:** Al ser 744 nulos se decidio reemplazar los valores faltantes (NaN) de Year por un valor representativo, que en este caso seria la mediana. Se decidió no eliminar los registros debido a que implicaría la pérdida de información relevante.

In [72]:
# Ver la mediana de la columna Year
df_wines['Year'].median()

2016.0

In [73]:
# Imputar (rellenar los nulos)
df_wines['Year'] = df_wines['Year'].fillna(df_wines['Year'].median())

In [74]:
# Verificar que ya no existan nulos
df_wines.isnull().sum()

Name               0
Country            0
Region             0
Winery             0
Rating             0
NumberOfRatings    0
Price              0
Year               0
WineStyle          0
dtype: int64

Ahora que estamos seguros que no existen nulos pasemos a la siguiente fase

In [79]:
# Mostramos los nombres de las columnas
df_wines.columns

Index(['Name', 'Country', 'Region', 'Winery', 'Rating', 'NumberOfRatings',
       'Price', 'Year', 'WineStyle'],
      dtype='object')

**Realizaremos un mapeo de datos**
* Name: Categórico Nominal
* Country: Categórico Nominal
* Region: Categórico Nominal
* Winery: Categórico Nominal
* Rating: Numérico Continuo
* NumberOfRatings: Numérico Discreto
* Price: Numérico Continuo
* Year: Numérico Discreto
* WineStyle: Categórico Nominal

**Clasificación de Variables**

* **Categórico Nominal:** Categorías sin un orden o jerarquía específica.
  * Ejemplo: Country, Region, WineStyle, Winery.

* **Categórico Ordinal:** Categorías que siguen un orden lógico o escala.
  * Ejemplo: (En este dataset no se identifican variables ordinales explícitas)

* **Numérico Discreto:** Valores que surgen de un conteo y no admiten decimales.
  * Ejemplo: NumberOfRatings, Year.

* **Numérico Continuo:** Valores que resultan de una medición y pueden tener decimales infinitos.
  * Ejemplo: Price, Rating.

**Comenzamos el análisis de las columnas categoricas**

In [81]:
# Nos mostrará la cantidad de categoricas distintas unicas de Name
df_wines['Name'].value_counts()

Name
Chardonnay 2018                                                                 78
Sauvignon Blanc 2019                                                            66
Sauvignon Blanc 2018                                                            51
Cabernet Sauvignon 2017                                                         43
Chardonnay 2017                                                                 41
Cabernet Sauvignon 2016                                                         41
Cabernet Sauvignon 2015                                                         35
Riesling Trocken 2018                                                           27
Crianza 2016                                                                    27
Chardonnay 2019                                                                 26
Pinot Noir 2017                                                                 25
Brunello di Montalcino 2015                                                     25
Pinot Grigio 2018                                                               23
Cabernet Sauvignon 2018                                                         23
Pinot Noir 2016                                                                 22
Merlot 2016                                                                     22
Chianti Classico 2016                                                           21
Sauvignon Blanc 2017                                                            21
Pomerol 2016                                                                    20
Merlot 2017                                                                     20
Brunello di Montalcino 2012                                                     20
Merlot 2018                                                                     19
Chardonnay 2016                                                                 19
Pomerol 2015                                                                    19
Chablis 2018                                                                    18
Pinot Noir 2018                                                                 18
Brunello di Montalcino 2014                                                     18
Cabernet Sauvignon 2014                                                         18
Shiraz 2017                                                                     17
Saint-Émilion Grand Cru (Grand Cru Classé) 2005                                 16
Saint-Émilion Grand Cru 2015                                                    16
Pinot Grigio 2019                                                               16
Pinot Noir 2015                                                                 15
Crianza 2015                                                                    14
Syrah 2017                                                                      14
Pinotage 2017                                                                   14
Barolo 2015                                                                     14
Riesling 2018                                                                   14
Reserva 2014                                                                    13
Brunello di Montalcino 2013                                                     13
Haut-Médoc 2016                                                                 13
Haut-Médoc 2015                                                                 13
Shiraz 2016                                                                     13
Rosé 2019                                                                       12
Chenin Blanc 2019                                                               12
Pomerol 2005                                                                    12
Brut Rosé N.V.                                                                  12
Rosso di Montalcino 2017                                                        12
Margaux (Grand Cru Classé) 2016                                                 12
Saint-Émilion Grand Cru (Grand Cru Classé) 2016                                 11
Syrah 2016                                                                      11
Haut-Médoc 2014                                                                 11
Merlot 2015                                                                     11
Shiraz 2018                                                                     11
Pomerol 2012                                                                    11
Chenin Blanc 2018                                                               11
Pauillac (Grand Cru Classé) 2016                                                11
Reserva 2015                                                                    11
Rosé 2018                                                                       11
Sancerre Blanc 2018                                                             10
Tinto 2016                                                                      10
Saint-Émilion Grand Cru 2016                                                    10
Nero d'Avola 2017                                                               10
Tempranillo 2018                                                                10
Saint-Estèphe 2016                                                              10
Médoc 2015                                                                      10
Malbec 2018                                                                     10
Nero d'Avola 2018                                                               10
Saint-Julien (Grand Cru Classé) 2016                                            10
Zinfandel 2017                                                                   9
Brut Rosé Champagne N.V.                                                         9
Saint-Julien (Grand Cru Classé) 2005                                             9
Amarone della Valpolicella Classico 2015                                         9
Saint-Julien (Grand Cru Classé) 2015                                             9
Bordeaux 2016                                                                    9
Rosso di Montalcino 2018                                                         9
Châteauneuf-du-Pape 2016                                                         9
Pomerol 2014                                                                     9
Médoc 2016                                                                       9
Riesling Brut N.V.                                                               9
Tinto 2018                                                                       9
Riesling 2017                                                                    9
Brut N.V.                                                                        9
Saint-Émilion Grand Cru (Grand Cru Classé) 2015                                  9
Syrah 2018                                                                       9
Prosecco N.V.                                                                    9
Weissburgunder Trocken 2018                                                      9
Saint-Émilion Grand Cru (Premier Grand Cru Classé) 2013                          8
Sauvignon Blanc 2016                                                             8
Chianti Classico 2015                                                            8
Chianti Classico 2017                                                            8
Brut Champagne N.V.                                                              8
Blanco 2018                                                                      8
Crianza 2014                                                                     8
Bordeaux Supérieur 2016                                                          8
Riesling Trocken 2016                                                            8
Médoc 2014                                                                       8
Pauillac (Grand Cru Classé) 2015                                                 8
Barbera d'Alba 2018                                                              8
Blaufränkisch 2017                                                               8
Margaux (Grand Cru Classé) 2005                                                  8
Riesling Trocken 2017                                                            8
Chianti 2018                                                                     8
Zweigelt 2017                                                                    8
Valpolicella Classico 2018                                                       8
Tinto 2017                                                                       8
Pauillac (Grand Cru Classé) 2017                                                 7
Rioja Reserva 2014                                                               7
Reserva 2012                                                                     7
Cabernet Sauvignon 2019                                                          7
Gran Reserva 2012                                                                7
Rosso di Montalcino 2016                                                         7
Pessac-Léognan (Grand Cru Classé de Graves) 2016                                 7
Saint-Émilion Grand Cru (Premier Grand Cru Classé) 2017                          7
Primitivo 2018                                                                   7
Margaux (Grand Cru Classé) 2014                                                  7
Rosso di Montalcino 2015                                                         7
Margaux (Grand Cru Classé) 2015                                                  7
Bordeaux Supérieur 2015                                                          7
Viognier 2018                                                                    7
Lagrein 2018                                                                     7
Saint-Julien (Grand Cru Classé) 2017                                             7
Margaux 2016                                                                     7
Pinotage 2018                                                                    7
Shiraz 2015                                                                      6
Haut-Médoc 2011                                                                  6
Montepulciano d'Abruzzo 2017                                                     6
Weissburgunder 2018                                                              6
Bardolino 2018                                                                   6
Riesling Trocken 2019                                                            6
Margaux (Grand Cru Classé) 2017                                                  6
Pomerol 2011                                                                     6
Malbec 2017                                                                      6
Pessac-Léognan (Grand Cru Classé de Graves) 2005                                 6
Prosecco Treviso Extra Dry N.V.                                                  6
Pinotage 2016                                                                    6
Primitivo di Manduria 2018                                                       6
Saint-Julien (Grand Cru Classé) 2009                                             6
Haut-Médoc 2012                                                                  6
Syrah 2015                                                                       6
Verdejo 2018                                                                     6
Barolo 2013                                                                      6
Tinto 2015                                                                       6
Vino Nobile di Montepulciano 2016                                                6
Gewürztraminer 2018                                                              6
Blanc de Blancs Brut Champagne N.V.                                              6
Pessac-Léognan 2005                                                              6
Pauillac (Grand Cru Classé) 2011                                                 6
Rosado 2018                                                                      6
Zinfandel 2016                                                                   6
Spätburgunder 2017                                                               6
Verdejo 2019                                                                     6
Côtes de Provence Rosé 2019                                                      6
Tinto 2013                                                                       6
Prosecco Extra Dry N.V.                                                          6
Gavi 2018                                                                        6
Amarone della Valpolicella 2015                                                  6
Rioja Reserva 2013                                                               5
Prosecco Brut N.V.                                                               5
Rosado 2019                                                                      5
Brunello di Montalcino Riserva 2010                                              5
Extra Brut Champagne N.V.                                                        5
Valdobbiadene Prosecco Superiore Brut N.V.                                       5
Malbec 2016                                                                      5
Shiraz 2019                                                                      5
Pomerol 2013                                                                     5
Barolo 2016                                                                      5
Dolcetto d'Alba 2018                                                             5
Rioja Reserva 2015                                                               5
Haut-Médoc 2005                                                                  5
Barbaresco 2016                                                                  5
Châteauneuf-du-Pape 2015                                                         5
Bordeaux Supérieur 2017                                                          5
Merlot 2019                                                                      5
Carmenère 2017                                                                   5
Pauillac (Grand Cru Classé) 2014                                                 5
Saint-Estèphe 2015                                                               5
Reserva 2013                                                                     5
Brunello di Montalcino 2011                                                      5
Barbaresco 2014                                                                  5
Pinotage 2019                                                                    5
Margaux 2005                                                                     5
Pinot Noir 2014                                                                  5
Spätburgunder Trocken 2017                                                       5
Saint-Julien (Grand Cru Classé) 2014                                             5
Saint-Émilion Grand Cru 2010                                                     5
Roble 2018                                                                       5
Blanc de Noirs Brut Champagne N.V.                                               5
Saint-Émilion Grand Cru (Grand Cru Classé) 2010                                  5
Saint-Émilion Grand Cru 2011                                                     5
Saint-Émilion Grand Cru (Premier Grand Cru Classé) 2014                          5
Châteauneuf-du-Pape 2017                                                         5
Pauillac (Grand Cru Classé) 2005                                                 5
Cabernet Sauvignon 2013                                                          5
Saint-Émilion Grand Cru (Premier Grand Cru Classé) 2011                          5
Saint-Émilion Grand Cru 2013                                                     5
Chianti 2017                                                                     5
Saint-Julien (Grand Cru Classé) 2011                                             5
Vernaccia di San Gimignano 2018                                                  5
Chardonnay 2015                                                                  5
Côtes du Rhône 2018                                                              5
Pinotage 2015                                                                    5
Saint-Émilion Grand Cru (Grand Cru Classé) 2008                                  5
Saint-Émilion Grand Cru 2005                                                     5
Lugana 2019                                                                      5
Gewürztraminer 2019                                                              5
Pouilly-Fumé 2018                                                                5
Fronsac 2005                                                                     5
Saint-Julien (Grand Cru Classé) 2010                                             5
Petit Chablis 2018                                                               5
Carmenère 2018                                                                   5
Sauvignon Blanc Trocken 2019                                                     4
Viognier 2017                                                                    4
Saint-Julien (Grand Cru Classé) 2012                                             4
Bardolino Chiaretto 2019                                                         4
Margaux (Grand Cru Classé) 2008                                                  4
Saint-Émilion Grand Cru 2014                                                     4
Primitivo 2017                                                                   4
Bourgogne Pinot Noir 2017                                                        4
Chianti Classico Riserva 2015                                                    4
Lalande-de-Pomerol 2016                                                          4
Barolo 2011                                                                      4
Saint-Estèphe 2005                                                               4
Saint-Émilion Grand Cru (Premier Grand Cru Classé) 2010                          4
Toscana 2016                                                                     4
Prosecco Frizzante N.V.                                                          4
Cabernet Sauvignon - Merlot 2016                                                 4
Moulis-en-Médoc 2014                                                             4
Viognier 2016                                                                    4
Grauburgunder 2019                                                               4
Saint-Émilion Grand Cru 2012                                                     4
Moulis-en-Médoc 2016                                                             4
Cabernet Sauvignon - Merlot 2017                                                 4
Rioja Crianza 2016                                                               4
Saint-Julien (Grand Cru Classé) 2008                                             4
Médoc 2012                                                                       4
Moulis-en-Médoc 2015                                                             4
Rosé Brut N.V.                                                                   4
Chablis 2017                                                                     4
Saint-Julien (Grand Cru Classé) 2006                                             4

In [82]:
# Ver cantidad de únicos de Name
df_wines['Name'].nunique()

10934

Podemos ver que la variable Name presenta una alta cardinalidad, con 10.934 valores únicos, lo que indica que la mayoría de los registros son distintos. Debido a esto, la variable no aporta valor predictivo, por lo que se estara evaluando su eliminacion del análisis

In [85]:
# Nos mostrará la cantidad de categoricas distintas unicas de Country
df_wines['Country'].value_counts()

Country
Italy             3919
France            3436
Spain             1533
Germany           1229
South Africa       846
United States      530
Austria            492
Chile              431
Portugal           336
Australia          318
Argentina          308
New Zealand        165
Brazil              50
Romania             37
Greece              25
Israel              23
Switzerland         23
Hungary             19
Slovenia            18
Lebanon             16
Moldova             16
Luxembourg          14
Georgia             13
Turkey              10
Croatia              6
Uruguay              5
United Kingdom       3
Canada               3
China                3
Bulgaria             2
Slovakia             2
Czech Republic       2
Mexico               1
Name: count, dtype: int64

In [86]:
# Ver cantidad de únicos de Country
df_wines['Country'].nunique()

33

La variable Country presenta un total de 33 categorías distintas. Esto indica que existe una diversidad moderada de países, lo que puede aportar valor al modelo al capturar diferencias geográficas en las características del vino.

In [87]:
# Nos mostrará la cantidad de categoricas distintas unicas de Region
df_wines['Region'].value_counts()

Region
Rioja                                              385
Stellenbosch                                       337
Pfalz                                              331
Toscana                                            307
Champagne                                          263
Südtirol - Alto Adige                              227
Mosel                                              217
Saint-Émilion Grand Cru                            207
Terre Siciliane                                    176
Barolo                                             175
Brunello di Montalcino                             168
Ribera del Duero                                   166
Rheinhessen                                        163
Chianti Classico                                   159
Burgenland                                         157
Mendoza                                            149
California                                         143
Rheingau                                           137
Baden                                              134
Pays d'Oc                                          132
Veneto                                             129
Marlborough                                        124
Pomerol                                            118
Western Cape                                       113
Saint-Julien                                       110
Margaux                                            109
Colchagua Valley                                   108
Nahe                                               105
Puglia                                             104
Douro                                              100
Châteauneuf-du-Pape                                100
Haut-Médoc                                          98
Salento                                             94
Pauillac                                            93
Pessac-Léognan                                      88
Napa Valley                                         87
Alentejano                                          86
Central Valley                                      86
Bordeaux                                            81
Langhe                                              79
Sicilia                                             78
Priorat                                             76
Côtes-du-Rhône                                      73
Saint-Estèphe                                       73
Alsace                                              69
Côtes de Provence                                   67
McLaren Vale                                        63
Primitivo di Manduria                               62
Barbera d'Alba                                      62
Montepulciano d'Abruzzo                             61
Wachau                                              60
Coastal Region                                      58
South Australia                                     58
Cava                                                57
Prosecco                                            56
Bandol                                              56
Chianti                                             55
Médoc                                               54
Navarra                                             54
Rueda                                               53
Conegliano-Valdobbiadene Prosecco                   53
Niederösterreich                                    53
Paarl                                               52
Rosso di Montalcino                                 51
Bourgogne                                           51
Aconcagua Valley                                    51
Barbaresco                                          50
Barossa                                             50
Barbera d'Asti                                      49
Castilla                                            49
Franciacorta                                        48
Sancerre                                            48
Franschhoek                                         48
Penedès                                             48
Castilla y León                                     48
Maipo Valley                                        46
Gigondas                                            45
La Mancha                                           45
Amarone della Valpolicella Classico                 45
Chablis                                             45
Robertson                                           44
delle Venezie                                       43
Columbia Valley                                     43
Uco Valley                                          42
Casablanca Valley                                   42
Bordeaux Supérieur                                  42
Valpolicella Ripasso                                41
Maremma Toscana                                     41
Swartland                                           39
Tupungato                                           39
Lugana                                              39
Barossa Valley                                      38
Amarone della Valpolicella                          37
Languedoc                                           37
Bolgheri                                            36
Hermitage                                           36
Vigneti delle Dolomiti                              35
Südsteiermark                                       35
Trentino-Alto Adige                                 34
Valencia                                            34
Somontano                                           34
Vin de France                                       34
Catalunya                                           34
Vino Nobile di Montepulciano                        33
Kamptal                                             33
Alentejo                                            33
Valpolicella                                        33
Cahors                                              32
Ahr                                                 32
Gavi                                                32
Crozes-Hermitage                                    32
Franken                                             31
Piemonte                                            31
Champagne Premier Cru                               30
Dolcetto d'Alba                                     30
Rías Baixas                                         30
Bolgheri Superiore                                  30
Venezia Giulia                                      28
Lalande-de-Pomerol                                  27
Prosecco di Treviso                                 27
Bierzo                                              27
Binissalem-Mallorca                                 26
Dão                                                 26
Etna                                                26
Côte-Rôtie                                          26
Toro                                                25
Côtes Catalanes                                     25
Cannonau di Sardegna                                25
Colli Orientali del Friuli                          25
Walker Bay                                          25
Salice Salentino                                    24
South Eastern Australia                             24
Côtes de Gascogne                                   24
Corbières                                           23
Pouilly-Fumé                                        23
Trentino                                            23
Lisboa                                              23
Galilee                                             23
Mittelburgenland                                    23
Jumilla                                             23
Mallorca                                            22
Rapel Valley                                        22
Fronsac                                             22
Saint-Joseph                                        22
Umbria                                              22
Constantia                                          21
Collio                                              21
Elgin                                               21
Friuli-Venezia Giulia                               21
Montsant                                            21
Moulis-en-Médoc                                     21
Valpolicella Classico                               21
Terre di Chieti                                     20
Bardolino                                           20
Durbanville                                         20
Serra Gaúcha                                        20
Campo de Borja                                      19
Maule Valley                                        19
Vermentino di Sardegna                              19
Monferrato                                          19
Neusiedlersee                                       19
Russian River Valley                                19
Pouilly-Fuissé                                      19
Carnuntum                                           18
Costières-de-Nîmes                                  18
Roero                                               18
Cariñena                                            18
Rosso Veronese                                      18
Morellino di Scansano                               18
Ventoux                                             18
Chinon                                              18
Valdepeñas                                          17
Livermore Valley                                    17
Gevrey-Chambertin                                   17
Languedoc-Roussillon                                17
Dominio de Valdepusa                                17
Castillon - Côtes de Bordeaux                       17
Trento                                              17
Crémant d'Alsace                                    17
Dealu Mare                                          17
Vinho Verde                                         16
Kremstal                                            16
South Eastern                                       16
Lombardia                                           16
Sonoma Coast                                        16
Côtes du Roussillon Villages                        16
Bekaa Valley                                        16
Nuits-Saint-Georges                                 16
Isola dei Nuraghi                                   16
Calabria                                            15
Valdeorras                                          15
Crémant de Loire                                    15
Côtes du Roussillon                                 15
Minervois                                           15
Clare Valley                                        15
Valtellina Superiore                                15
Garda                                               15
Saumur                                              15
Rosso di Montepulciano                              15
La Clape                                            15
Terra Alta                                          15
Verona                                              15
Wiltingen                                           14
Menfi                                               14
Corton-Charlemagne Grand Cru                        14
Moscato d'Asti                                      14
Cirò                                                14
Lujan de Cuyo                                       14
Carignano del Sulcis                                14
Campania                                            14
Hawke's Bay                                         14
Langhorne Creek                                     14
Condrieu                                            13
Wien                                                13
Kakheti                                             13
San Juan                                            13
Weinviertel                                         13
Vernaccia di San Gimignano                          13
Costers del Segre                                   13
Lodi                                                13
Chianti Colli Senesi                                13
Encruzilhada do Sul                                 13
Verdicchio dei Castelli di Jesi                     12
Irpinia                                             12
Sonoma County                                       12
Central Coast                                       12
Salta                                               12
Côtes de Thongue                                    12
Los Carneros                                        12
Bairrada                                            12
Eden Valley                                         12
Calatayud                                           12
Graves                                              12
Teroldego Rotaliano                                 11
Rioja Alta                                          11
Pic-Saint-Loup                                      11
Vino d'Italia                                       11
Soave Classico                                      11
Washington                                          11
Lazio                                               11
Provence                                            11
Monterey                                            11
Hemel-en-Aarde Valley                               11
Rosso Piceno                                        11
Emilia-Romagna                                      11
Muscadet-Sevre et Maine                             10
Abruzzo                                             10
Fleurie                                             10
Aglianico del Vulture                               10
Luberon                                             10
Meursault                                           10
Faugères                                            10
Margaret River                                      10
Rasteau                                             10
Pla de Bages                                        10
Citrusdal Mountain                                  10
Champagne Grand Cru                                 10
Neusiedlersee-Hügelland                             10
Crémant de Limoux                                   10
Crémant de Bourgogne                                10
Wagram                                              10
Thrace                                               9
Saint-Émilion                                        9
Trebbiano d'Abruzzo                                  9
Valpolicella Ripasso Classico                        9
Lanzarote                                            9
Montagne-Saint-Émilion                               9
Bianco di Custoza                                    9
Mâcon-Villages                                       9
Venezia                                              9
Wiener Gemischter Satz                               9
Cortona                                              9
Podravje                                             9
Utiel-Requena                                        9
Beaujolais-Villages                                  9
Wellington                                           9
Aconcagua Costa                                      9
Cádiz                                                9
Madiran                                              8
Côtes de Bourg                                       8
Bolgheri Sassicaia                                   8
Alicante                                             8
Riverina                                             8
Vosne-Romanée                                        8
Friuli Grave                                         8
Listrac-Médoc                                        8
Aconcagua                                            8
Dry Creek Valley                                     8
Beaujolais                                           8
Chianti Rùfina                                       8
Wehlen                                               8
Saale-Unstrut                                        8
Pomino                                               8
Oakville                                             8
Anderson Valley                                      8
Bardolino Classico                                   8
Montefalco                                           8
Terrasses du Larzac                                  8
Dundee Hills                                         8
Nebbiolo d'Alba                                      8
Fiano de Avellino                                    8
Vale dos Vinhedos                                    8
Petit Chablis                                        8
Tunuyán                                              8
North Coast                                          8
St. Helena                                           8
Cape Town                                            7
Breede River Valley                                  7
Itata Valley                                         7
Zürich                                               7
Sta. Rita Hills                                      7
Thermenregion                                        7
Valtellina                                           7
Loire Valley                                         7
Marche                                               7
Almansa                                              7
Minervois La Livinière                               7
Coteaux Varois en Provence                           7
Vouvray                                              7
Vacqueyras                                           7
Württemberg                                          7
Cornas                                               7
Willamette Valley                                    7
Soave                                                7
Champagne Grand Cru 'Aÿ'                             7
Peumo                                                7
Yecla                                                7
Taurasi                                              7
Brauneberg                                           7
Friuli Isonzo                                        7
Península de Setúbal                                 7
Plà i Llevant                                        7
Castel del Monte                                     7
Vin de Pays                                          6
Lirac                                                6
Steiermark                                           6
Reggiano                                             6
Alsace Grand Cru                                     6
Tavel                                                6
Tejo                                                 6
Uclés                                                6
Puligny-Montrachet                                   6
Monção e Melgaço                                     6
Malepère                                             6
Rio Grande do Sul                                    6
Villány                                              6
Morgon                                               6
Romagna                                              6
Leyda Valley                                         6
Mercurey                                             6
Empordà                                              6
Alghero                                              6
Mendocino County                                     6
German Wine                                          6
Walla Walla Valley                                   6
Sopron                                               6
Val di Neto                                          6
Molise                                               6
Viré-Clessé                                          5
Côtes-du-Rhône-Villages                              5
Monterey County                                      5
Gard                                                 5
Vermentino di Gallura                                5

In [88]:
# Ver cantidad de únicos de Region
df_wines['Region'].nunique()

861

Podemos observar que la variable Region presenta 861 categorías distintas, lo que indica una alta cardinalidad. Esto puede generar problemas en el modelo al aumentar considerablemente la dimensionalidad del dataset. Por lo tanto, se estara evaluando su eliminacion

In [89]:
# Nos mostrará la cantidad de categoricas distintas unicas de Winery
df_wines['Winery'].value_counts()

Winery
Markus Molitor                                            73
Errazuriz                                                 58
Torres                                                    54
Joseph Drouhin                                            51
Gaja                                                      42
M. Chapoutier                                             42
E. Guigal                                                 36
Antinori                                                  36
Paul Jaboulet Aîné                                        36
Von Winning                                               34
Château de Saint Cosme                                    33
Gérard Bertrand                                           33
Fontanafredda                                             32
Penfolds                                                  31
Niepoort                                                  31
Francis Ford Coppola                                      31
Delas                                                     30
Wittmann                                                  30
Knipser                                                   29
d'Arenberg                                                28
Caliterra                                                 28
Marqués de Riscal                                         27
Salentein                                                 26
Planeta                                                   26
Tasca d'Almerita                                          26
Paul Mas                                                  26
Masi                                                      26
Farnese                                                   26
Vite Colte                                                26
Baron Philippe de Rothschild                              25
Weingut Bründlmayer                                       25
St. Michael-Eppan                                         25
Ruffino                                                   25
Ramón Bilbao                                              25
Heinrich                                                  25
Cusumano                                                  24
Louis Jadot                                               24
Colterenzio (Schreckbichl)                                24
Calmel & Joseph                                           24
Emrich-Schönleber                                         24
Zenato                                                    23
Ricasoli                                                  23
Dr. Von Bassermann-Jordan                                 23
San Marzano                                               23
Nals Margreid                                             22
Vietti                                                    22
Lenotti                                                   21
Andeluna                                                  21
Tardieu-Laurent                                           21
Van Volxem                                                21
Trapiche                                                  21
Domaine de la Janasse                                     21
Schneider                                                 21
Weingut Metzger                                           21
Epicuro                                                   21
Simonsig                                                  21
Spier                                                     20
Firriato                                                  20
Zonin                                                     20
Louis Latour                                              20
Domäne Wachau                                             20
Peter Lehmann                                             20
Nederburg                                                 20
Tommasi                                                   20
Salwey                                                    19
Bouchard Père & Fils                                      19
Gut Hermannsberg                                          19
Feudi di San Gregorio                                     19
Château Léoville Las Cases                                19
Famille Perrin                                            19
Kühling-Gillot                                            19
Avignonesi                                                19
Schloss Lieser                                            19
Ceretto                                                   19
Villa Maria                                               18
Santa Rita                                                18
Miguel Torres                                             18
Mezzacorona                                               18
Louis Roederer                                            18
Baglio di Pianetto                                        18
Reichsrat von Buhl                                        18
Wente                                                     18
Bellavista                                                18
Tramin                                                    18
Dönnhoff                                                  18
Morgenster Estate                                         18
Barons de Rothschild (Lafite)                             18
Robert Mondavi                                            17
Montes                                                    17
Les Jamelles                                              17
Boschendal                                                17
Boekenhoutskloof                                          17
Cantina Kaltern                                           17
Rocca delle Macìe                                         17
Tormaresca                                                17
Bodegas Valdemar                                          17
Domaine Lafage                                            17
Prunotto                                                  17
Domaine Bousquet                                          17
Varvaglione                                               17
Les Héritiers du Comte Lafon                              16
Enate                                                     16
Yalumba                                                   16
Dr. Bürklin-Wolf                                          16
Château Purcari                                           16
Telmo Rodriguez                                           16
Falesco                                                   16
Banfi                                                     16
Friedrich Becker                                          16
Oliver Zeter                                              16
Langmeil                                                  16
Gallo Family Vineyards                                    16
Creation                                                  16
Cecilia Beretta                                           16
Château Musar                                             16
Saint Clair                                               16
Elvio Cogno                                               16
Protos                                                    15
Lidio Carraro                                             15
Kleine Zalze                                              15
Cortes de Cima                                            15
Barone Montalto                                           15
Chateau Ste. Michelle                                     15
Schäfer-Fröhlich                                          15
Ziereisen                                                 15
Feudo Arancio                                             15
Markowitsch                                               15
Viñas del Vero                                            15
Château Ducru-Beaucaillou                                 15
G.D. Vajra                                                15
Montes Alpha                                              15
Elena Walch                                               15
Stellenrust                                               15
Muga                                                      15
Braida                                                    15
Alois Lageder                                             15
Brancaia                                                  15
Terlan (Terlano)                                          15
Allegrini                                                 15
Villa Sandi                                               14
Vigneti del Salento                                       14
Ferrari                                                   14
Marqués de Griñon                                         14
MAN                                                       14
Sartori                                                   14
Livio Felluga                                             14
Nino Negri                                                14
Kaiken                                                    14
Marco Felluga                                             14
Argiolas                                                  14
El Coto                                                   14
Philipp Kuhn                                              14
Château Léoville Barton                                   14
Trimbach                                                  14
Castello Monaci                                           14
Henri Bourgeois                                           14
Georg Breuer                                              14
Poliziano                                                 14
Mauro Molino                                              14
Fleur du Cap                                              14
Tenuta delle Terre Nere                                   14
Lis Neris                                                 14
Borgo Molino                                              14
Los Vascos                                                14
Corte Giara                                               14
La Spinetta                                               14
Château de Beaucastel                                     14
Hugel                                                     14
Poggio Al Tesoro                                          13
Faiveley                                                  13
Bruno Giacosa                                             13
Sella & Mosca                                             13
Gnarly Head                                               13
Baron de Ley                                              13
Marqués de Cáceres                                        13
Château Belair-Monange                                    13
Mukhrani                                                  13
Giacomo Fenocchio                                         13
Loimer                                                    13
Donnafugata                                               13
Weingut R&A Pfaffl                                        13
Catena Zapata                                             13
Borgogno                                                  13
Robert Weil                                               13
Álvaro Palacios                                           13
Viña Maipo                                                13
Muratie                                                   13
Beringer                                                  13
Frescobaldi                                               13
Château Sociando-Mallet                                   13
Caparzo                                                   13
Domaine Henri Boillot                                     13
Maximin Grünhaus                                          12
Schloss Vollrads                                          12
Cos d'Estournel                                           12
Carmen                                                    12
Grant Burge                                               12
Mouton Cadet                                              12
Taylors / Wakefield                                       12
Château Montrose                                          12
Meerlust                                                  12
Mazzei                                                    12
Terres Dorées                                             12
Herdade dos Grous                                         12
Petra                                                     12
Librandi                                                  12
Paul Achs                                                 12
Tenuta San Guido                                          12
Tua Rita                                                  12
Claus Preisinger                                          12
Raumland                                                  12
Castillo Perelada                                         12
Tenuta CastelGiocondo                                     12
Velenosi                                                  12
Tement                                                    12
Peter Jakob Kühn                                          12
Neethlingshof Estate                                      12
Pinord                                                    12
Bruno Paillard                                            12
Cà dei Frati                                              12
Esporão                                                   12
Wieninger                                                 12
Torbreck                                                  11
Valdivieso                                                11
Zeni                                                      11
Schola Sarmenti                                           11
Altesino                                                  11
Château Brane-Cantenac                                    11
Bodega Finca Las Moras                                    11
Tenuta Il Poggione                                        11
Enzo Boglietti                                            11
Bouvet-Ladubay                                            11
Scheiblhofer                                              11
Mesa                                                      11
Domenico Clerico                                          11
Hacienda López de Haro                                    11
Langlois-Chateau                                          11
Bodega Piedra Negra                                       11
Gesellmann                                                11
Taittinger                                                11
Tokara                                                    11
Santa Ema                                                 11
Rings                                                     11
Ciacci Piccolomini d'Aragona                              11
Dominus                                                   11
Heger                                                     11
Piper-Heidsieck                                           11
Leopard’s Leap                                            11
Santadi                                                   11
Meyer - Näkel                                             11
De Wetshof                                                11
Springfield Estate                                        11
Château Moulin Haut-Laroque                               11
Tenute Silvio Nardi                                       11
Tianna Negre                                              11
Jean Leon                                                 11
Apaltagua                                                 11
Delheim                                                   11
Joh. Jos. Prüm                                            11
Ornellaia                                                 10
Château Gombaude-Guillot                                  10
Georg Mosbacher                                           10
Borsao                                                    10
Château Giscours                                          10
Neil Ellis                                                10
Foradori                                                  10
Bibi Graetz                                               10
Castello di Gabbiano                                      10
Weingut Holger Koch                                       10
Château de Fieuzal                                        10
Val d'Oca                                                 10
Elio Grasso                                               10
Vergelegen                                                10
Domaine de Terrebrune                                     10
Cielo e Terra                                             10
Lungarotti                                                10
Stemmari                                                  10
Manincor                                                  10
Isole e Olena                                             10
Emiliana                                                  10
Abadal                                                    10
Château Mouton Rothschild                                 10
Castelfeder                                               10
La Motte Wine Estate                                      10
Coppo                                                     10
Monte del Frá                                             10
Château Branaire-Ducru                                    10
Château Langoa Barton                                     10
MontGras                                                  10
Viña Cobos                                                10
Cune (CVNE)                                               10
Arunda                                                    10
Lan                                                       10
Kaapzicht                                                 10
Deutz                                                     10
Château Lascombes                                         10
Abadia Retuerta                                           10
Fortant                                                   10
Domaines Ott                                              10
Kanonkop                                                  10
Bogle                                                     10
Tenuta Rapitalà                                           10
Domaines Schlumberger                                     10
TerraNoble                                                10
Marqués de Murrieta                                       10
Dreissigacker                                              9
Bodegas Langa                                              9
Puklavec Family Wines                                      9
Kloster Eberbach                                           9
Joseph Perrier                                             9
Kollwentz                                                  9
Xavier Vignon                                              9
Ansgar Clüsserath                                          9
Geyser Peak                                                9
Castello di Ama                                            9
Aldo Conterno                                              9
Cederberg                                                  9
Baigorri                                                   9
Durbanville Hills                                          9
Edetària                                                   9
Ottella                                                    9
Fetzer                                                     9
Château Léoville Poyferré                                  9
Cinciole                                                   9
Hermon                                                     9
Lionel Osmin & Cie                                         9
Domaine de la Tour du Bon                                  9

In [90]:
# Ver cantidad de únicos de Winery
df_wines['Winery'].nunique()

3505

Podemos observar que la variable Winery presenta un total de 3.505 categorías distintas, lo que indica una alta cardinalidad. Esto implica que la mayoría de las bodegas son únicas. Debido a esto, la variable no aporta valor predictivo relevante en relación con su complejidad, por lo que se evaluara eliminarla del análisis.

In [91]:
# Nos mostrará la cantidad de categoricas distintas unicas de WineStyle
df_wines['WineStyle'].value_counts()

WineStyle
red          8666
white        3764
sparkling    1007
rose          397
Name: count, dtype: int64

In [92]:
# Ver cantidad de únicos de WineStyle
df_wines['WineStyle'].nunique()

4

Podemos observar que la variable WineStyle presenta un total de 4 categorías distintas: red, white, sparkling y rose. Esto indica que la variable tiene una baja cardinalidad, lo que la hace adecuada para ser utilizada en el modelo.

In [97]:
df_wines = df_wines.drop(columns=['Name', 'Winery'])

**Se decidió eliminar las columnas Name y Winery debido a su alta cardinalidad, ya que presentan una gran cantidad de categorías únicas, lo que podría aumentar innecesariamente la dimensionalidad del dataset y afectar negativamente el rendimiento del modelo.**

In [101]:
# Verificar que se eliminaron
df_wines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13834 entries, 0 to 13833
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country          13834 non-null  object
 1   Region           13834 non-null  object
 2   Rating           13834 non-null  float64
 3   NumberOfRatings  13834 non-null  int64
 4   Price            13834 non-null  float64
 5   Year             13834 non-null  float64
 6   WineStyle        13834 non-null  object
dtypes: float64(3), int64(1), object(3)
memory usage: 756.7+ KB

In [ ]:
#------------------------------------------------------------

**Estadistica descriptiva a las variables numericas**

In [98]:
df_wines.describe()

             Rating  NumberOfRatings         Price          Year
count  13834.000000     13834.000000  13834.000000  13834.000000
mean       3.865664       428.322466     33.024850   2015.556961
std        0.296427      1838.413812     70.899893      3.188885
min        2.200000        25.000000      3.150000   1961.000000
25%        3.700000        56.000000      9.902500   2015.000000
50%        3.900000       129.000000     15.950000   2016.000000
75%        4.100000       336.000000     32.500000   2018.000000
max        4.900000     94287.000000   3410.790000   2020.000000

Se identifican 4 variables numericas lo cual es correcto con respecto a lo que identificamos antes

**Importaremos las librerias para realizar el encoder a Country, Region y WineStyle**

In [95]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.9/85.9 kB 4.0 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

In [102]:
from sklearn.preprocessing import OneHotEncoder
import category_encoders as ce

In [106]:
# Aplicar OneHotEncoder a Country y WineStyle
# Esto convierte esas columnas categóricas en columnas numéricas.
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

ohe_encoded = ohe.fit_transform(df_wines[['Country', 'WineStyle']])

Esto convierte las columnas categóricas Country y WineStyle en columnas numéricas.

In [107]:
# Convertir este resultado a DataFrame
ohe_df = pd.DataFrame(
    ohe_encoded,
    columns=ohe.get_feature_names_out(['Country', 'WineStyle']),
    index=df_wines.index
)

Esto transforma el resultado del encoder en una tabla normal con nombres de columnas claros.

In [108]:
# Aplicar Binary Encoding a Region
be = ce.BinaryEncoder(cols=['Region'])

region_encoded = be.fit_transform(df_wines[['Region']])

Convierte Region en varias columnas numéricas, pero sin generar 861 columnas como haría OneHot.

In [109]:
# Unir todo en un nuevo dataframe final
df_final = pd.concat(
    [
        df_wines.drop(columns=['Country', 'WineStyle', 'Region']),
        ohe_df,
        region_encoded
    ],
    axis=1
)

Para poder utilizar las variables categóricas en el modelo, fue necesario transformarlas a formato numérico mediante técnicas de encoding.

En el caso de las variables Country y WineStyle, se aplicó One-Hot Encoding, ya que cuentan con un número reducido de categorías. Este método consiste en crear una columna por cada categoría, permitiendo representar cada valor de forma independiente sin generar conflictos en el modelo.

Por otro lado, la variable Region presenta una gran cantidad de categorías (alta cardinalidad). Si se aplicara One-Hot Encoding, se generarían demasiadas columnas, lo que afectaría el rendimiento del modelo. Por esta razón, se utilizó Binary Encoding, una técnica que permite representar las categorías utilizando un menor número de columnas mediante combinaciones binarias, logrando así reducir la dimensionalidad del dataset.

In [110]:
df_final.head()

,Rating,NumberOfRatings,Price,Year,Country_Argentina,Country_Australia,Country_Austria,Country_Brazil,Country_Bulgaria,Country_Canada,Country_Chile,Country_China,Country_Croatia,Country_Czech Republic,Country_France,Country_Georgia,Country_Germany,Country_Greece,Country_Hungary,Country_Israel,Country_Italy,Country_Lebanon,Country_Luxembourg,Country_Mexico,Country_Moldova,Country_New Zealand,Country_Portugal,Country_Romania,Country_Slovakia,Country_Slovenia,Country_South Africa,Country_Spain,Country_Switzerland,Country_Turkey,Country_United Kingdom,Country_United States,Country_Uruguay,WineStyle_red,WineStyle_rose,WineStyle_sparkling,WineStyle_white,Region_0,Region_1,Region_2,Region_3,Region_4,Region_5,Region_6,Region_7,Region_8,Region_9
0,4.2,100,95.00,2011.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,1
1,4.3,100,15.50,2017.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,1,0
2,3.9,100,7.45,2015.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,1,1
3,3.5,100,8.72,2019.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0,0,0,0,0,1,0,0
4,3.9,100,29.15,2016.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0,0,0,0,0,1,0,1

In [112]:
print(f"Total de columnas del nuevo dataframe: {len(df_final.columns)}")

Total de columnas del nuevo dataframe: 51